version: 2

sources:
  - name: erpnorthwind20211010
    description: tabelas nortwind
    tables:
      - name: public_orders
        description: >
          tabela fato ordens
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null

      - name: public_orders_details
        
      - name: public_shippers
        
      - name: public_categories

      - name: public_customers

      - name: public_employee_territories

      - name: public_employee

      - name: public_products

      - name: public_regions

      - name: public_suppliers

      - name: public_territories
       